name: Deploy to Development

on:
  push:
    branches: [ develop ]  # develop 브랜치에 push될 때 실행

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        # Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: yarn install --frozen-lockfile
      #build
      - name: Build
        run: yarn build
      # check aws credential
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2
      # zip
      - name: Generate deployment package
        run: |
          rm -rf node_modules/.cache
          zip -r deploy.zip . -x "*.git*"
      # deploy
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: aiff-front
          environment_name: development-aiff-front
          version_label: ${{ github.sha }}
          region: ap-northeast-2
          deployment_package: deploy.zip